#spring:
#  application:
#    name: Messages
#
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      username: root
#      password: root
#      database: Messages_ChatApp
#      authentication-database: admin
#
#server:
#  port: 8080


spring:
  application:
    name: Messages

  data:
    mongodb:
      uri: mongodb://root:root@localhost:27018/Messages_ChatApp?authSource=admin

server:
  port: 8080
