version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - 27018:27017
    volumes:
      - mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    command: [--auth]  # THIS IS CRUCIAL - ENABLES AUTHENTICATION
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')" -u root -p root --authenticationDatabase admin
      interval: 5s
      timeout: 30s
      retries: 3

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin  # Important for auth

volumes:
  mongo: